version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - wp_db_volume:/var/lib/mysql
      - ./db-data/wordpress.sql:/docker-entrypoint-initdb.d/install_wordpress.sql
    restart: always
    env_file: .env

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    restart: always

  wordpress:
    depends_on:
      - db
    image: wordpress:5.9.3
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
    env_file: .env
    volumes:
      - ./uploads:/var/www/html/wp-content/uploads
      - ./plugins:/var/www/html/wp-content/plugins

volumes:
  wp_db_volume:
